version: "3"

services:
  ac:
    image: ogbanugot/avenieca:0.3.0
    command: twin --config "/avenieca/ac.json"
    volumes:
      - "ac:/avenieca/storage"
      - "./configs/docker/twins/ac.json:/avenieca/ac.json"
      - "./configs/docker/ras/ac_ras.json:/avenieca/ac_ras.json"
    networks:
      - ECACluster
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 20
        window: 120s
  aqi:
    image: ogbanugot/avenieca:0.3.0
    command: twin --config "/avenieca/aqi.json"
    volumes:
      - "aqi:/avenieca/storage"
      - "./configs/docker/twins/aqi.json:/avenieca/aqi.json"
      - "./configs/docker/ras/aqi_ras.json:/avenieca/aqi_ras.json"
    networks:
      - ECACluster
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 20
        window: 120s

  occupancy:
    image: ogbanugot/avenieca:0.3.0
    command: twin --config "/avenieca/occupancy.json"
    volumes:
      - "occupancy:/avenieca/storage"
      - "./configs/docker/twins/occupancy.json:/avenieca/occupancy.json"
      - "./configs/docker/ras/occupancy_ras.json:/avenieca/occupancy_ras.json"
    networks:
      - ECACluster
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 20
        window: 120s

  purifier:
    image: ogbanugot/avenieca:0.3.0
    command: twin --config "/avenieca/purifier.json"
    volumes:
      - "purifier:/avenieca/storage"
      - "./configs/docker/twins/purifier.json:/avenieca/purifier.json"
      - "./configs/docker/ras/purifier_ras.json:/avenieca/purifier_ras.json"
    networks:
      - ECACluster
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 20
        window: 120s

  temperature:
    image: ogbanugot/avenieca:0.3.0
    command: twin --config "/avenieca/temperature.json"
    volumes:
      - "temperature:/avenieca/storage"
      - "./configs/docker/twins/temperature.json:/avenieca/temperature.json"
      - "./configs/docker/ras/temperature_ras.json:/avenieca/temperature_ras.json"
    networks:
      - ECACluster
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 20
        window: 120s

volumes:
  ac:
    driver: local
  aqi:
    driver: local
  occupancy:
    driver: local
  temperature:
    driver: local
  purifier:
    driver: local

networks:
  ECACluster: