version: "3"

services:
  server:
    image: ogbanugot/avenieca-server:0.3.0
    command: --config "/avenieca/server.json"
    volumes:
      - "server:/avenieca/storage"
      - "./configs/docker/recsys_server.json:/avenieca/server.json"
    ports:
      - "2580:2580"
    networks:
      - ECACluster
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 20
        window: 120s

volumes:
#  aggregate:
#    driver: local
#  core_us:
#    driver: local
#  core_pp:
#    driver: local
#  core_res:
#    driver: local
#  document:
#    driver: local
  server:
    driver: local

networks:
  ECACluster: