version: "3"

services:
  server:
    image: avenieca/server:0.4.0
    command: --config "/avenieca/server.json"
    volumes:
      - "server:/avenieca/storage"
      - "./configs/docker/recsys_server.json:/avenieca/server.json"
    ports:
      - "2580:2580"
    networks:
      - ECACluster
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 20
        window: 120s

volumes:
  server:
    driver: local

networks:
  ECACluster: