version: "3"

services:
  core_us:
    image: avenieca/eca:0.4.0
    command: core-us --config "/avenieca/core_us.json"
    volumes:
      - "core_us:/avenieca/storage"
      - "./configs/docker/core_us.json:/avenieca/core_us.json"
      - "./license.lic:/avenieca/license.lic"
    networks:
      - ECACluster
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 20
        window: 120s

  core_pp:
    image: avenieca/eca:0.4.0
    command: core-pp --config "/avenieca/core_pp.json"
    volumes:
      - "core_pp:/avenieca/storage"
      - "./configs/docker/core_pp.json:/avenieca/core_pp.json"
      - "./license.lic:/avenieca/license.lic"
    networks:
      - ECACluster
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 20
        window: 120s

  core_res:
    image: avenieca/eca:0.4.0
    command: core-respond --config "/avenieca/core_res.json"
    volumes:
      - "core_res:/avenieca/storage"
      - "./configs/docker/core_res.json:/avenieca/core_res.json"
      - "./license.lic:/avenieca/license.lic"
    depends_on:
      - core_pp
    networks:
      - ECACluster
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 20
        window: 120s

volumes:
  core_us:
    driver: local
  core_pp:
    driver: local
  core_res:
    driver: local

networks:
  ECACluster: